name: PIERWSZY DODATEK

on:
  push:
    branches: [master]

env:
  REG: ghcr.io

jobs:
  build-and-push:
    name: Buduję i publikuję obrazy
    runs-on: ubuntu-latest

    steps:
      - name: Pobieram kod za pomocą checkout
        uses: actions/checkout@v2

      - name: Konfiguruję QEMU
        uses: docker/setup-qemu-action@v1

      - name: Konfiguruję Buildx
        uses: docker/setup-buildx-action@v1

      - name: Loguję się do rejestru GitHuba
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REG }}
          username: ${{ github.actor }}
          password: ${{ secrets.SEKRETY_GITHUBA }}

      - name: Loguję się do repozytorium DockerHuba
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Buduję i publikuję
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm/v7, linux/arm64/v8, linux/amd64
          push: true
          tags: |
            ${{ github.repository }},${{ env.REG }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha
